# permissions for end users to view opensimulators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: opensimulator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opensimulatoroperator
    app.kubernetes.io/part-of: opensimulatoroperator
    app.kubernetes.io/managed-by: kustomize
  name: opensimulator-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - opensimulators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - opensimulators/status
  verbs:
  - get
