# permissions for end users to edit opensimulatorroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensimulatorroute-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - opensimulatorroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - opensimulatorroutes/status
  verbs:
  - get
